Conferences Views, Controller and Models Added
GuziyV/Scientific-report-ASP.NET-Core-MVC- pull request #15
Opened 2019-04-07 16:22 UTC by AndryushkaYO

2019-04-07 18:54 UTC, vhuzii requested changes

2019-04-07 18:54 UTC, GuziyV commented on ScientificReport/ScientificReport/Controllers/ConferencesController.cs
> +        static private IConference _assets;
чому `_assets` а не `conferenceService` ?

2019-04-07 18:54 UTC, GuziyV commented on ScientificReport/ScientificReport/Views/Conferences/Index.cshtml
> +    <div class="item col-md-4  align-items-center justify-content-center text-center " style="padding:20px 0; ">
Будь ласка не використовуй інлайн стилі, а пиши їх в окремих файлах, потім легше буде їх дописувати і міняти, але те що ти використовуєш бутстрап класи це плюс

2019-04-07 18:54 UTC, GuziyV commented on ScientificReport/ScientificReportServices/ConferenceService.cs
> +        public DateTime getDateById(int Id)
Цей(і чотири нижні методи) зайві(на мою думку), чому просто не писати `conferenceService.getById(id).Date` ?

2019-04-07 18:54 UTC, GuziyV commented on ScientificReport/ScientificReportServices/IConference.cs
> +    public interface IConference
Чому `IConference` а не `IConferenceService`

2019-04-07 18:54 UTC, GuziyV commented on ScientificReport/ScientificReport/Controllers/ConferencesController.cs
> +        static private IConference _assets;
Чому `static` ?

2019-04-07 18:59 UTC, vhuzii requested changes

2019-04-07 18:59 UTC, GuziyV commented on ScientificReport/ScientificReportData/ScientificReportData.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
Чому ти добавила `ScientificReportData` i `ScientificReportServices` як окремий проект а не `Class Library` ??

2019-04-07 19:31 UTC, GuziyV commented
Можливо краще переназвати `ScientificReportServices` в `Business logic` і там добавити папку `Services` ?

2019-04-07 19:56 UTC, GuziyV commented on ScientificReport/ScientificReportData/ScientificReportData.csproj
> +    <TargetFramework>netcoreapp2.1</TargetFramework>
чому `2.1` ? я думав ми використовуємо `2.2`

2019-04-08 13:27 UTC, AndryushkaYO commented on ScientificReport/ScientificReport/Views/Conferences/Index.cshtml
> +    <div class="item col-md-4  align-items-center justify-content-center text-center " style="padding:20px 0; ">
Я знаю. Просто я  не встигала. І треба було вже показувати. тому я швидко туди записала. Я то зміню

2019-04-08 13:28 UTC, AndryushkaYO commented on ScientificReport/ScientificReportServices/ConferenceService.cs
> +        public DateTime getDateById(int Id)
Згідна. Зайві. Можеш видалити

2019-04-08 13:40 UTC, AndryushkaYO commented on ScientificReport/ScientificReportServices/IConference.cs
> +    public interface IConference
Мені вже отто казали((

2019-04-08 13:41 UTC, AndryushkaYO commented on ScientificReport/ScientificReportData/ScientificReportData.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
він так казав: що робити окремими проектами

2019-04-08 13:41 UTC, AndryushkaYO commented on ScientificReport/ScientificReportData/ScientificReportData.csproj
> +    <TargetFramework>netcoreapp2.1</TargetFramework>
Володь просто перероби на правильне. я не профі. я не знала(((

2019-04-11 09:13 UTC, GuziyV commented on ScientificReport/ScientificReportData/ScientificReportData.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
![Untitled](https://user-images.githubusercontent.com/35489438/55945286-2a1b8b80-5c53-11e9-9d1a-639d373d1a32.png)

2019-04-11 09:41 UTC, AndryushkaYO commented on ScientificReport/ScientificReportData/ScientificReportData.csproj
> +<Project Sdk="Microsoft.NET.Sdk">
ну супер, на парі не казав таке... ладно то можна переробити

2019-04-17 20:23 UTC, merged