Publications create
GuziyV/Scientific-report-ASP.NET-Core-MVC- pull request #28
Opened 2019-04-29 20:39 UTC by KhymeraEvr

2019-04-29 20:42 UTC, KhymeraEvr commented on ScientificReport/ScientificReport/Controllers/PublicationController.cs
> +                    new Author { Name = name };
курва

2019-04-30 07:35 UTC, vhuzii requested changes

2019-04-30 07:35 UTC, GuziyV commented on ScientificReport/ScientificReport/Controllers/PublicationController.cs
> +        private readonly UnitOfWork _unitOfWork;
Якшо ми збиралися розділяти базу і контролери, то тут має бути сервіс а не `uow`

2019-04-30 07:35 UTC, GuziyV commented on ScientificReport/ScientificReport/Views/Publication/Components/PublicationComponent.cs
> +        public UnitOfWork _unitOfWork;
Те ж саме що вище

2019-04-30 07:35 UTC, GuziyV commented on ScientificReport/ScientificReportData/UnitOfWork.cs
> +        public Author GetAuthorByName(string name)
Це в репозиторії треба зробити(створити інтерфейс `IAuthorRepository : IRepository<Author, int>` потім `AuthorRepository : IAuthorRepository ` в якому буде метод `GetAuthorName`)

2019-05-01 06:51 UTC, GuziyV commented on ScientificReport/ScientificReportData/Migrations/20190430164224_updateModels.cs
> +    public partial class updateModels : Migration
Погана назва для міграції :D, але хай там..

2019-05-05 15:42 UTC, merged