User, Report, Publication, DbContext added
GuziyV/Scientific-report-ASP.NET-Core-MVC- pull request #9
Opened 2019-03-21 21:25 UTC by KhymeraEvr

2019-03-22 09:24 UTC, GuziyV commented
Створюй енами в окремих файлах пліз

2019-03-26 05:06 UTC, vhuzii requested changes

2019-03-26 05:06 UTC, GuziyV commented on ScientificReport/ScientificReport/Data/Models/Enums.cs
> +    public enum Role
Cтворюй енами в окремих файлах пліз

2019-03-26 05:06 UTC, GuziyV commented on ScientificReport/ScientificReport/Data/Models/Report.cs
> +        [Key]
Можливо краще добавити [DatabaseGenerated(DatabaseGeneratedOption.Identity)] також(автоінкремент) до всіх ентіті

2019-03-27 06:38 UTC, vhuzii requested changes
І зареєструй пліз DbContext

2019-03-28 19:44 UTC, merged